---
apiVersion: v1
kind: Namespace
metadata:
  name: brabbit
  labels:
    name: brabbit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boombox
  labels:
    app: boombox
  namespace: brabbit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boombox
  template:
    metadata:
      labels:
        app: boombox
    spec:
      containers:
      - name: boombox
        image: denhamparry/app-9172e898aef006d7952c374cd9e7bbae:latest
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: napster
  namespace: brabbit
spec:
  selector:
    app: boombox
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
---
