version: "3.8"

services:
#  gitlab:
#    container_name: "foobar-git"
#    image: 'gitlab/gitlab-ce:latest'
#    hostname: 'git.foobar.com'
#    ports:
#      - '9080:80'
#      - '9022:22'
#      - '9443:443'
#    volumes:
#      - '$GITLAB_HOME/data/git-data:/var/opt/gitlab/git-data'
#      - '$GITLAB_HOME/data/gitaly:/var/opt/gitlab/gitaly'
#      - '$GITLAB_HOME/data/postgresql:/var/opt/gitlab/postgresql'
#    shm_size: '256m'

  localstack:
    container_name: "foobar-saas"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - EDGE_PORT=4566
      - SERVICES=S3
