apiVersion: v1
kind: Namespace
metadata:
  name: the-homer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: the-homer-sa
  namespace: the-homer
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: the-homer-secret
  annotations:
    kubernetes.io/service-account.name: "the-homer-sa"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: the-homer-viewer
  namespace: the-homer
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["get", "list", "delete", "patch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: the-homer-rb
  namespace: the-homer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: the-homer-viewer
subjects:
  - kind: ServiceAccount
    name: the-homer-sa
    namespace: the-homer
---
apiVersion: v1
kind: Pod
metadata:
  name: homer-pod
  namespace: the-homer
spec:
  containers:
  - name: homer-pod
    image: cgr.dev/chainguard/nginx:latest
    ports:
    - containerPort: 80
