apiVersion: v1
kind: Namespace
metadata:
  name: the-homer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: the-homer-sa
  namespace: the-homer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role:viewer
  namespace: the-homer
rules:
  - apiGroups:
      - ''      
    resources:
      - services
      - pods
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: the-homer-rb
  namespace: the-homer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role:viewer
subjects:
  - kind: ServiceAccount
    name: the-homer-sa
    namespace: the-homer
