apiVersion: v1
kind: Pod
metadata:
  name: homer-pod-priv
  namespace: the-homer
spec:
  hostPID: true
  hostNetwork: true
  containers:
  - name: homer-pod-priv
    image: nginx:latest
    ports:
    - containerPort: 80
    securityContext:
      privileged: true